name: ngo_backend

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  mongo_dart: ^0.10.3
  dart_jsonwebtoken: ^2.12.1
  bcrypt: ^1.1.3
  dotenv: ^4.1.0
  http: ^1.2.0
  crypto: ^3.0.3
  mailer: ^6.1.0